require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  Exclude:
    - vendor/**/*
    - bin/*
    - lib/proto/**/*
    - node_modules/**/*
    - db/schema.rb
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s+)#']
  Exclude:
    - db/seeds.rb
    - config/environments/production.rb
Lint/RaiseException:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - db/migrate/*
Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
    - config/environments/production.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
Rails/Output:
  Exclude:
    - db/seeds.rb
