AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - vendor/**/*
    - bin/*
    - node_modules/**/*
    - db/schema.rb
Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s+)#']
  Exclude:
    - db/seeds.rb
    - config/environments/production.rb
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - db/migrate/*
Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
    - config/environments/production.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
