# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/address.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('proto/address.proto', syntax: :proto3) do
    add_message 'proto.Address' do
      optional :id, :string, 1
      optional :zipcode, :string, 2
      optional :prefecture_phonetic, :string, 3
      optional :city_phonetic, :string, 4
      optional :town_area_phonetic, :string, 5
      optional :additional_area_phonetic, :string, 6
      optional :prefecture, :string, 7
      optional :city, :string, 8
      optional :town_area, :string, 9
      optional :additional_area, :string, 10
    end
  end
end

module Proto
  Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.Address').msgclass
end
