# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/address_list_response.proto

require 'google/protobuf'

require 'proto/address_pb'
require 'proto/page_meta_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('proto/address_list_response.proto', syntax: :proto3) do
    add_message 'proto.AddressListResponse' do
      optional :page, :message, 1, 'proto.PageMeta'
      repeated :data, :message, 2, 'proto.Address'
    end
  end
end

module Proto
  AddressListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.AddressListResponse').msgclass
end
