# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/page_meta.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/page_meta.proto", :syntax => :proto3) do
    add_message "proto.PageMeta" do
      optional :total, :int32, 1
      optional :number, :int32, 2
      optional :size, :int32, 3
    end
  end
end

module Proto
  PageMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.PageMeta").msgclass
end
