default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/<%= ENV['RAILS_ENV'] || 'development' %>.sqlite3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
